# Generated by Django 5.0.7 on 2024-08-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_schoolformmodel_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='age',
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='home_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='marital_status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='occupation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='passport_expire_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='passport_issue_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='passport_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='place_of_birth',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='present_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
