# Generated by Django 5.0.7 on 2024-08-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_studentmodel_age_studentmodel_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmodel',
            old_name='marital_status',
            new_name='company_name1',
        ),
        migrations.RenameField(
            model_name='studentmodel',
            old_name='home_address',
            new_name='current_address',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='present_address',
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='company_name2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='date_of_entry1',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='date_of_entry2',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='date_of_retirement1',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='date_of_retirement2',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='elementary_school_date_of_enrollment',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='elementary_school_date_of_graduation',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='elementary_school_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='high_school_date_of_completion',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='high_school_date_of_enrollment',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='high_school_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='junior_high_school_date_of_completion',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='junior_high_school_date_of_enrollment',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='junior_high_school_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='occupation1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='occupation2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='spouse_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='university_date_of_completion',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='university_date_of_enrollment',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='university_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='vocational_school_date_of_completion',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='vocational_school_date_of_enrollment',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='vocational_school_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
