# Generated by Django 5.0.7 on 2024-08-07 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_marital_status_studentmodel_company_name1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmodel',
            old_name='high_school_date_of_completion',
            new_name='high_school_date_of_graduation',
        ),
        migrations.RenameField(
            model_name='studentmodel',
            old_name='junior_high_school_date_of_completion',
            new_name='junior_high_school_date_of_graduation',
        ),
        migrations.RenameField(
            model_name='studentmodel',
            old_name='university_date_of_completion',
            new_name='university_date_of_graduation',
        ),
        migrations.RenameField(
            model_name='studentmodel',
            old_name='vocational_school_date_of_completion',
            new_name='vocational_school_date_of_graduation',
        ),
    ]
