# Generated by Django 5.0.7 on 2024-07-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolformmodel',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
